# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Kelembaban(models.Model):
    tanggal = models.DateField(primary_key=True, auto_now=False, auto_now_add=False, blank=True)
    jam0 = models.IntegerField(default=0)
    jam1 = models.IntegerField(default=0)
    jam2 = models.IntegerField(default=0)
    jam3 = models.IntegerField(default=0)
    jam4 = models.IntegerField(default=0)
    jam5 = models.IntegerField(default=0)
    jam6 = models.IntegerField(default=0)
    jam7 = models.IntegerField(default=0)
    jam8 = models.IntegerField(default=0)
    jam9 = models.IntegerField(default=0)
    jam10 = models.IntegerField(default=0)
    jam11 = models.IntegerField(default=0)
    jam12 = models.IntegerField(default=0)
    jam13 = models.IntegerField(default=0)
    jam14 = models.IntegerField(default=0)
    jam15 = models.IntegerField(default=0)
    jam16 = models.IntegerField(default=0)
    jam17 = models.IntegerField(default=0)
    jam18 = models.IntegerField(default=0)
    jam19 = models.IntegerField(default=0)
    jam20 = models.IntegerField(default=0)
    jam21 = models.IntegerField(default=0)
    jam22 = models.IntegerField(default=0)
    jam23 = models.IntegerField(default=0)
#    rata = models.IntegerField()
 #   maksimum = models.IntegerField()
  #  minimum = models.IntegerField()
    publish = models.DateField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return 'Tanggal: {0} Jam0: {1}'.format(self.tanggal, self.jam0)

class Suhu(models.Model):
    tanggal = models.DateField(primary_key=True, auto_now=False, auto_now_add=False, blank=True)
    jam0 = models.FloatField(default=0)
    jam1 = models.FloatField(default=0)
    jam2 = models.FloatField(default=0)
    jam3 = models.FloatField(default=0)
    jam4 = models.FloatField(default=0)
    jam5 = models.FloatField(default=0)
    jam6 = models.FloatField(default=0)
    jam7 = models.FloatField(default=0)
    jam8 = models.FloatField(default=0)
    jam9 = models.FloatField(default=0)
    jam10 = models.FloatField(default=0)
    jam11 = models.FloatField(default=0)
    jam12 = models.FloatField(default=0)
    jam13 = models.FloatField(default=0)
    jam14 = models.FloatField(default=0)
    jam15 = models.FloatField(default=0)
    jam16 = models.FloatField(default=0)
    jam17 = models.FloatField(default=0)
    jam18 = models.FloatField(default=0)
    jam19 = models.FloatField(default=0)
    jam20 = models.FloatField(default=0)
    jam21 = models.FloatField(default=0)
    jam22 = models.FloatField(default=0)
    jam23 = models.FloatField(default=0)
#    rata = models.FloatField()
 #   maksimum = models.FloatField()
  #  minimum = models.FloadField()
    publish = models.DateField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return 'Tanggal: {0} Jam0: {1}'.format(self.tanggal, self.jam0)

class Tekanan(models.Model):
    tanggal = models.DateField(primary_key=True, auto_now=False, auto_now_add=False, blank=True)
    jam0 = models.FloatField(default=0)
    jam1 = models.FloatField(default=0)
    jam2 = models.FloatField(default=0)
    jam3 = models.FloatField(default=0)
    jam4 = models.FloatField(default=0)
    jam5 = models.FloatField(default=0)
    jam6 = models.FloatField(default=0)
    jam7 = models.FloatField(default=0)
    jam8 = models.FloatField(default=0)
    jam9 = models.FloatField(default=0)
    jam10 = models.FloatField(default=0)
    jam11 = models.FloatField(default=0)
    jam12 = models.FloatField(default=0)
    jam13 = models.FloatField(default=0)
    jam14 = models.FloatField(default=0)
    jam15 = models.FloatField(default=0)
    jam16 = models.FloatField(default=0)
    jam17 = models.FloatField(default=0)
    jam18 = models.FloatField(default=0)
    jam19 = models.FloatField(default=0)
    jam20 = models.FloatField(default=0)
    jam21 = models.FloatField(default=0)
    jam22 = models.FloatField(default=0)
    jam23 = models.FloatField(default=0)
#    rata = models.FloatField()
 #   maksimum = models.FloatField()
  #  minimum = models.FloadField()
    publish = models.DateField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return 'Tanggal: {0} Jam0: {1}'.format(self.tanggal, self.jam0)

class Angin(models.Model):
    tanggal = models.DateField(primary_key=True, auto_now=False, auto_now_add=False, blank=True)
    jam0 = models.CharField(max_length=6, blank=True, default=0)
    jam1 = models.CharField(max_length=6, blank=True, default=0)
    jam2 = models.CharField(max_length=6, blank=True, default=0)
    jam3 = models.CharField(max_length=6, blank=True, default=0)
    jam4 = models.CharField(max_length=6, blank=True, default=0)
    jam5 = models.CharField(max_length=6, blank=True, default=0)
    jam6 = models.CharField(max_length=6, blank=True, default=0)
    jam7 = models.CharField(max_length=6, blank=True, default=0)
    jam8 = models.CharField(max_length=6, blank=True, default=0)
    jam9 = models.CharField(max_length=6, blank=True, default=0)
    jam10 = models.CharField(max_length=6, blank=True, default=0)
    jam11 = models.CharField(max_length=6, blank=True, default=0)
    jam12 = models.CharField(max_length=6, blank=True, default=0)
    jam13 = models.CharField(max_length=6, blank=True, default=0)
    jam14 = models.CharField(max_length=6, blank=True, default=0)
    jam15 = models.CharField(max_length=6, blank=True, default=0)
    jam16 = models.CharField(max_length=6, blank=True, default=0)
    jam17 = models.CharField(max_length=6, blank=True, default=0)
    jam18 = models.CharField(max_length=6, blank=True, default=0)
    jam19 = models.CharField(max_length=6, blank=True, default=0)
    jam20 = models.CharField(max_length=6, blank=True, default=0)
    jam21 = models.CharField(max_length=6, blank=True, default=0)
    jam22 = models.CharField(max_length=6, blank=True, default=0)
    jam23 = models.CharField(max_length=6, blank=True, default=0)
#    rata = models.CharField(max_length=6, blank=True, default=0)
 #   maksimum = models.CharField(max_length=6, blank=True, default=0)
  #  minimum = models.CharField(max_length=6, blank=True, default=0)
    publish = models.DateField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return 'Tanggal: {0} Jam0: {1}'.format(self.tanggal, self.jam0)

class Radiasi(models.Model):
    tanggal = models.DateField(primary_key=True, auto_now=False, auto_now_add=False, blank=True)
    R_06_07 = models.CharField(max_length=4, blank=True, default=0)
    R_07_08 = models.CharField(max_length=4, blank=True, default=0)
    R_08_09 = models.CharField(max_length=4, blank=True, default=0)
    R_09_10 = models.CharField(max_length=4, blank=True, default=0)
    R_10_11 = models.CharField(max_length=4, blank=True, default=0)
    R_11_12 = models.CharField(max_length=4, blank=True, default=0)
    R_12_13 = models.CharField(max_length=4, blank=True, default=0)
    R_13_14 = models.CharField(max_length=4, blank=True, default=0)
    R_14_15 = models.CharField(max_length=4, blank=True, default=0)
    R_15_16 = models.CharField(max_length=4, blank=True, default=0)
    R_16_17 = models.CharField(max_length=4, blank=True, default=0)
    R_17_18 = models.CharField(max_length=4, blank=True, default=0)
    R_18_19 = models.CharField(max_length=2, blank=True, default=0)
    R_19_20 = models.CharField(max_length=2, blank=True, default=0)
    R_20_21 = models.CharField(max_length=2, blank=True, default=0)
    R_21_22 = models.CharField(max_length=2, blank=True, default=0)
    R_22_23 = models.CharField(max_length=2, blank=True, default=0)
    R_23_00 = models.CharField(max_length=2, blank=True, default=0)
    R_00_01 = models.CharField(max_length=2, blank=True, default=0)
    R_01_02 = models.CharField(max_length=2, blank=True, default=0)
    R_02_03 = models.CharField(max_length=2, blank=True, default=0)
    R_03_04 = models.CharField(max_length=2, blank=True, default=0)
    R_04_05 = models.CharField(max_length=2, blank=True, default=0)
    R_05_06 = models.CharField(max_length=2, blank=True, default=0)
#    jumlah = models.CharField(max_length=20, blank=True, default=0)
 #   total = models.CharField(max_length=20, blank=True, default=0)
    publish = models.DateField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return 'Tanggal: {0} R_06_07: {1}'.format(self.tanggal, self.R_06_07)
