# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-30 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelembaban',
            name='maksimum',
        ),
        migrations.RemoveField(
            model_name='kelembaban',
            name='minimum',
        ),
        migrations.RemoveField(
            model_name='kelembaban',
            name='rata',
        ),
    ]
