# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-01 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20191130_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suhu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam0', models.FloatField()),
                ('jam1', models.FloatField()),
                ('jam2', models.FloatField()),
                ('jam3', models.FloatField()),
                ('jam4', models.FloatField()),
                ('jam5', models.FloatField()),
                ('jam6', models.FloatField()),
                ('jam7', models.FloatField()),
                ('jam8', models.FloatField()),
                ('jam9', models.FloatField()),
                ('jam10', models.FloatField()),
                ('jam11', models.FloatField()),
                ('jam12', models.FloatField()),
                ('jam13', models.FloatField()),
                ('jam14', models.FloatField()),
                ('jam15', models.FloatField()),
                ('jam16', models.FloatField()),
                ('jam17', models.FloatField()),
                ('jam18', models.FloatField()),
                ('jam19', models.FloatField()),
                ('jam20', models.FloatField()),
                ('jam21', models.FloatField()),
                ('jam22', models.FloatField()),
                ('jam23', models.FloatField()),
                ('publish', models.DateField(auto_now=True)),
            ],
        ),
    ]
