# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-01 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_tekanan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam0', models.CharField(blank=True, max_length=6)),
                ('jam1', models.CharField(blank=True, max_length=6)),
                ('jam2', models.CharField(blank=True, max_length=6)),
                ('jam3', models.CharField(blank=True, max_length=6)),
                ('jam4', models.CharField(blank=True, max_length=6)),
                ('jam5', models.CharField(blank=True, max_length=6)),
                ('jam6', models.CharField(blank=True, max_length=6)),
                ('jam7', models.CharField(blank=True, max_length=6)),
                ('jam8', models.CharField(blank=True, max_length=6)),
                ('jam9', models.CharField(blank=True, max_length=6)),
                ('jam10', models.CharField(blank=True, max_length=6)),
                ('jam11', models.CharField(blank=True, max_length=6)),
                ('jam12', models.CharField(blank=True, max_length=6)),
                ('jam13', models.CharField(blank=True, max_length=6)),
                ('jam14', models.CharField(blank=True, max_length=6)),
                ('jam15', models.CharField(blank=True, max_length=6)),
                ('jam16', models.CharField(blank=True, max_length=6)),
                ('jam17', models.CharField(blank=True, max_length=6)),
                ('jam18', models.CharField(blank=True, max_length=6)),
                ('jam19', models.CharField(blank=True, max_length=6)),
                ('jam20', models.CharField(blank=True, max_length=6)),
                ('jam21', models.CharField(blank=True, max_length=6)),
                ('jam22', models.CharField(blank=True, max_length=6)),
                ('jam23', models.CharField(blank=True, max_length=6)),
                ('publish', models.DateField(auto_now=True)),
            ],
        ),
    ]
