# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-01 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_angin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiasiMthr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('R_06_07', models.FloatField()),
                ('R_07_08', models.FloatField()),
                ('R_08_09', models.FloatField()),
                ('R_09_10', models.FloatField()),
                ('R_10_11', models.FloatField()),
                ('R_11_12', models.FloatField()),
                ('R_12_13', models.FloatField()),
                ('R_13_14', models.FloatField()),
                ('R_14_15', models.FloatField()),
                ('R_15_16', models.FloatField()),
                ('R_16_17', models.FloatField()),
                ('R_17_18', models.FloatField()),
                ('R_18_19', models.FloatField()),
                ('R_19_20', models.FloatField()),
                ('R_20_21', models.FloatField()),
                ('R_21_22', models.FloatField()),
                ('R_22_23', models.FloatField()),
                ('R_23_00', models.FloatField()),
                ('R_00_01', models.FloatField()),
                ('R_01_02', models.FloatField()),
                ('R_02_03', models.FloatField()),
                ('R_03_04', models.FloatField()),
                ('R_04_05', models.FloatField()),
                ('R_05_06', models.FloatField()),
                ('publish', models.DateField(auto_now=True)),
            ],
        ),
    ]
