# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-01 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_radiasimthr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_00_01',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_01_02',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_02_03',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_03_04',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_04_05',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_05_06',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_06_07',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_07_08',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_08_09',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_09_10',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_10_11',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_11_12',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_12_13',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_13_14',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_14_15',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_15_16',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_16_17',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_17_18',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_18_19',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_19_20',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_20_21',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_21_22',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_22_23',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_23_00',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
