# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20191201_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelembaban',
            name='jam0',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam1',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam10',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam11',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam12',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam13',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam14',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam15',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam16',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam17',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam18',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam19',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam2',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam20',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam21',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam22',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam23',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam3',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam4',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam5',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam6',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam7',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam8',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam9',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
