# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20191202_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angin',
            name='jam0',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam1',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam10',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam11',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam12',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam13',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam14',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam15',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam16',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam17',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam18',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam19',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam2',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam20',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam21',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam22',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam23',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam3',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam4',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam5',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam6',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam7',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam8',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='angin',
            name='jam9',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam0',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam11',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam13',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam14',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam15',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam16',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam17',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam18',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam19',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam20',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam21',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam22',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam23',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='jam9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_00_01',
            field=models.CharField(blank=True, default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_01_02',
            field=models.CharField(blank=True, default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_02_03',
            field=models.CharField(blank=True, default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_03_04',
            field=models.CharField(blank=True, default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_04_05',
            field=models.CharField(blank=True, default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_05_06',
            field=models.CharField(blank=True, default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_06_07',
            field=models.CharField(blank=True, default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_07_08',
            field=models.CharField(blank=True, default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_08_09',
            field=models.CharField(blank=True, default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_09_10',
            field=models.CharField(blank=True, default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_10_11',
            field=models.CharField(blank=True, default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_11_12',
            field=models.CharField(blank=True, default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_12_13',
            field=models.CharField(blank=True, default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_13_14',
            field=models.CharField(blank=True, default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_14_15',
            field=models.CharField(blank=True, default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_15_16',
            field=models.CharField(blank=True, default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_16_17',
            field=models.CharField(blank=True, default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_17_18',
            field=models.CharField(blank=True, default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_18_19',
            field=models.CharField(blank=True, default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_19_20',
            field=models.CharField(blank=True, default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_20_21',
            field=models.CharField(blank=True, default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_21_22',
            field=models.CharField(blank=True, default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_22_23',
            field=models.CharField(blank=True, default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='radiasimthr',
            name='R_23_00',
            field=models.CharField(blank=True, default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam0',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam10',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam11',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam12',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam13',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam14',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam15',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam16',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam17',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam18',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam19',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam20',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam21',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam22',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam23',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam5',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam6',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam7',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam8',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='jam9',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam0',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam10',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam11',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam12',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam13',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam14',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam15',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam16',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam17',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam18',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam19',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam20',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam21',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam22',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam23',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam5',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam6',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam7',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam8',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='jam9',
            field=models.FloatField(default=0),
        ),
    ]
