# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20191202_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_00_01',
            new_name='r_00_01',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_01_02',
            new_name='r_01_02',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_02_03',
            new_name='r_02_03',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_03_04',
            new_name='r_03_04',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_04_05',
            new_name='r_04_05',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_05_06',
            new_name='r_05_06',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_06_07',
            new_name='r_06_07',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_07_08',
            new_name='r_07_08',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_08_09',
            new_name='r_08_09',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_09_10',
            new_name='r_09_10',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_10_11',
            new_name='r_10_11',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_11_12',
            new_name='r_11_12',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_12_13',
            new_name='r_12_13',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_13_14',
            new_name='r_13_14',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_14_15',
            new_name='r_14_15',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_15_16',
            new_name='r_15_16',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_16_17',
            new_name='r_16_17',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_17_18',
            new_name='r_17_18',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_18_19',
            new_name='r_18_19',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_19_20',
            new_name='r_19_20',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_20_21',
            new_name='r_20_21',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_21_22',
            new_name='r_21_22',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_22_23',
            new_name='r_22_23',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='R_23_00',
            new_name='r_23_00',
        ),
    ]
