# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20191202_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_00_01',
            new_name='r00',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_01_02',
            new_name='r01',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_02_03',
            new_name='r02',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_03_04',
            new_name='r03',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_04_05',
            new_name='r04',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_05_06',
            new_name='r05',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_06_07',
            new_name='r06',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_07_08',
            new_name='r07',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_08_09',
            new_name='r08',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_09_10',
            new_name='r09',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_10_11',
            new_name='r10',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_11_12',
            new_name='r11',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_12_13',
            new_name='r12',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_13_14',
            new_name='r13',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_14_15',
            new_name='r14',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_15_16',
            new_name='r15',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_16_17',
            new_name='r16',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_17_18',
            new_name='r17',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_18_19',
            new_name='r18',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_19_20',
            new_name='r19',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_20_21',
            new_name='r20',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_21_22',
            new_name='r21',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_22_23',
            new_name='r22',
        ),
        migrations.RenameField(
            model_name='radiasimthr',
            old_name='r_23_00',
            new_name='r23',
        ),
    ]
