# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-04 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20191202_0910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RadiasiMthr',
            new_name='Radiasi',
        ),
    ]
