# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-04 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20191204_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiasi',
            name='jumlah',
            field=models.CharField(blank=True, default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='radiasi',
            name='total',
            field=models.CharField(blank=True, default=0, max_length=5),
        ),
    ]
