# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-04 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20191204_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiasi',
            old_name='r00',
            new_name='R_00_01',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r01',
            new_name='R_01_02',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r02',
            new_name='R_02_03',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r03',
            new_name='R_03_04',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r04',
            new_name='R_04_05',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r05',
            new_name='R_05_06',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r06',
            new_name='R_06_07',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r07',
            new_name='R_07_08',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r08',
            new_name='R_08_09',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r09',
            new_name='R_09_10',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r10',
            new_name='R_10_11',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r11',
            new_name='R_11_12',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r12',
            new_name='R_12_13',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r13',
            new_name='R_13_14',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r14',
            new_name='R_14_15',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r15',
            new_name='R_15_16',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r16',
            new_name='R_16_17',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r17',
            new_name='R_17_18',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r18',
            new_name='R_18_19',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r19',
            new_name='R_19_20',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r20',
            new_name='R_20_21',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r21',
            new_name='R_21_22',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r22',
            new_name='R_22_23',
        ),
        migrations.RenameField(
            model_name='radiasi',
            old_name='r23',
            new_name='R_23_00',
        ),
    ]
