# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-09 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20191204_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kelembaban',
            options={'verbose_name': 'kelembaban', 'verbose_name_plural': 'kelembabans'},
        ),
    ]
