# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20191209_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kelembaban',
            options={},
        ),
        migrations.RemoveField(
            model_name='angin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='kelembaban',
            name='id',
        ),
        migrations.RemoveField(
            model_name='radiasi',
            name='id',
        ),
        migrations.RemoveField(
            model_name='radiasi',
            name='jumlah',
        ),
        migrations.RemoveField(
            model_name='radiasi',
            name='total',
        ),
        migrations.RemoveField(
            model_name='suhu',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tekanan',
            name='id',
        ),
        migrations.AlterField(
            model_name='angin',
            name='tanggal',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kelembaban',
            name='tanggal',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='radiasi',
            name='tanggal',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suhu',
            name='tanggal',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tekanan',
            name='tanggal',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
